import { OnDestroy } from '@angular/core';
import { Action, Store } from '@ngrx/store';
import { Actions } from '@ngrx/effects';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/of';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/concatAll';
import 'rxjs/add/operator/do';
import 'rxjs/add/operator/mapTo';
import 'rxjs/add/operator/mergeMap';
import 'rxjs/add/operator/switchMap';
import 'rxjs/add/operator/switchMapTo';
import 'rxjs/add/operator/take';
import 'rxjs/add/operator/toArray';
import 'rxjs/add/operator/withLatestFrom';
import 'rxjs/add/operator/takeWhile';
import 'rxjs/add/operator/takeUntil';
import { ApiDeleteFailAction, ApiDeleteSuccessAction, ApiGetFailAction, ApiGetInitAction, ApiGetSuccessAction, ApiPatchFailAction, ApiPatchSuccessAction, ApiQueryRefreshAction, LocalQueryFailAction, LocalQuerySuccessAction } from './actions';
import { NgrxJsonApi } from './api';
export declare class NgrxJsonApiEffects implements OnDestroy {
    private actions$;
    private jsonApi;
    private store;
    createResource$: Observable<Action>;
    updateResource$: Observable<ApiPatchSuccessAction | ApiPatchFailAction>;
    readResource$: Observable<ApiGetSuccessAction | ApiGetFailAction>;
    private localQueryInitEventFor(query);
    private removeQueryEventFor(query);
    queryStore$: Observable<LocalQuerySuccessAction | LocalQueryFailAction>;
    private executeLocalQuery(query);
    deleteResource$: Observable<ApiDeleteSuccessAction | ApiDeleteFailAction>;
    triggerReadOnQueryRefresh$: Observable<ApiGetInitAction>;
    refreshQueriesOnDelete$: Observable<ApiQueryRefreshAction>;
    private handlePendingCreate(pendingChange, zoneId);
    private handlePendingUpdate(pendingChange, zoneId);
    private handlePendingDelete(pendingChange, zoneId);
    applyResources$: Observable<any>;
    private config;
    constructor(actions$: Actions, jsonApi: NgrxJsonApi, store: Store<any>);
    ngOnDestroy(): void;
    private toApplyAction(actions, zoneId);
    private toErrorPayload(query, response);
    private generatePayload(resource, operation);
}
